project:
  type: website

execute: 
  echo: true
  fig-width: 10
  fig-height: 4.5

website:
  page-navigation: true
  title: "IME05-12532"
  description: "Análise de Sobrevivência"
  
  twitter-card:
    creator: "@r_accioly"
    image: "images/anasobre.png"

  page-footer:
    left: "Baseado em https://sta210-s22.github.io/website/"
    background: "#D9E3E4"
    
  sidebar:
    background: "#D9E3E4"
    logo: "images/anasobre.png"
    pinned: true
    align: center
    tools: 
      - icon: github
        href: https://github.com/raccioly20
        text: "GitHub"
      - icon: twitter
        href: https://twitter.com/r_accioly
        text: "Twitter"    

    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - section: "Informação da disciplina"
        contents:
          - href: visao-do-curso.qmd
            text: "Visão Geral"
          - href: index.qmd
            text: Cronograma
      - section: "RStudio Cloud"
        contents:
          - href: acesso-rstudio.qmd
            text: Acesso
      - section: "Conteúdo Semanal"
        contents:
          - href: semanas/Aula01.qmd
            text: "Aula01"
          - href: semanas/Aula02.qmd
            text: "Aula02"
          - href: semanas/Aula03.qmd
            text: "Aula03"
          - href: semanas/Aula04.qmd
            text: "Aula04"
          - href: semanas/Aula05.qmd
            text: "Aula05"
          - href: semanas/Aula06.qmd
            text: "Aula06"
          - href: semanas/Aula06x.qmd
            text: "TFA1"
          - href: semanas/Aula06x1.qmd
            text: "TFA2"
          - href: semanas/Aula07.qmd
            text: "TFA3"
          - href: semanas/Aula08.qmd
            text: "Cox 1"
          - href: semanas/Aula09.qmd
            text: "Cox 2"
          - href: semanas/Aula10.qmd
            text: "Cox 3"
          - href: semanas/Aula11.qmd
            text: "Cox 4"
          - href: semanas/Aula12.qmd
            text: "Cox 5"
          - href: semanas/Aula13.qmd
            text: "Cox 6"
          - href: semanas/Aula14.qmd
            text: "Cox 7"
 
 
 
 
 
 
format:
  html:
    theme:
      light: [cosmo, theme.scss]
      dark: [cosmo, theme-dark.scss]
    mainfont: "Atkinson Hyperlegible"
    code-copy: true
    code-overflow: wrap
    toc: true

freeze: auto

editor: visual

