{
  "hash": "61a5317a7c0691726e7e7f6f5a577d37",
  "result": {
    "markdown": "---\ntitle: \"Análise de Sobrevivência\"\nsubtitle: \"Modelos SemiParamétrico de Cox\"\nauthor: \"Ricardo Accioly\"\nformat:\n  revealjs:\n    theme: dark \n    slide-number: true\n    chalkboard: \n      buttons: false\n    preview-links: auto\n    css: styles.css\n---\n\n\n## Modelo SemiParamétrico de Cox {.smaller .scrollable}\n\nVamos usar neste exemplo dados da biblioteca survival.\nOs dados são de sobrevivência de pacientes com cancer de pulmão em estágio avançado do North Central Cancer Treatment Group.\n\n-   inst: Institution code (Código da instituição)\n-   time: Survival time in days (Tempo de sobrevivência em dias)\n-   status: censoring status 1=censored (censurado), 2=dead (morto)\n-   age: Age in years (Idade em anos)\n-   sex: Male=1 Female=2 (1=Homem, 2 = Mulher)\n-   ph.ecog: ECOG performance score as rated by the physician. 0=asymptomatic, 1= symptomatic but completely ambulatory, 2= in bed \\<50% of the day, 3= in bed \\> 50% of the day but not bedbound, 4 = bedbound\n-   ph.karno: Karnofsky performance score (bad=0-good=100) rated by physician\n-   pat.karno: Karnofsky performance score as rated by patient\n-   meal.cal: Calories consumed at meals\n-   wt.loss: Weight loss in last six months (pounds)\n\n\n## Carregando os dados\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(survival)\ndados <- lung\nstr(dados)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t228 obs. of  10 variables:\n $ inst     : num  3 3 3 5 1 12 7 11 1 7 ...\n $ time     : num  306 455 1010 210 883 ...\n $ status   : num  2 2 1 2 2 1 2 2 2 2 ...\n $ age      : num  74 68 56 57 60 74 68 71 53 61 ...\n $ sex      : num  1 1 1 1 1 1 2 2 1 1 ...\n $ ph.ecog  : num  1 0 0 1 0 1 2 2 1 2 ...\n $ ph.karno : num  90 90 90 90 100 50 70 60 70 70 ...\n $ pat.karno: num  100 90 90 60 90 80 60 80 80 70 ...\n $ meal.cal : num  1175 1225 NA 1150 NA ...\n $ wt.loss  : num  NA 15 15 11 0 0 10 1 16 34 ...\n```\n:::\n:::\n\n\nAnalisando vemos que o conjunto de dados tem 10 variáveis e 228 observações\n\n## Avaliando a presença de dados ausentes\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(complete.cases(lung))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 167\n```\n:::\n:::\n\n\nExistem 167 casos completos, ou seja, temos dados ausentes em algumas variáveis\n\n## Visualizando dados iniciais\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngt::gt(head(dados))\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"sgxraiwskv\" style=\"overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>html {\n  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;\n}\n\n#sgxraiwskv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#sgxraiwskv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 0;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#sgxraiwskv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#sgxraiwskv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#sgxraiwskv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#sgxraiwskv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#sgxraiwskv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#sgxraiwskv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sgxraiwskv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#sgxraiwskv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#sgxraiwskv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#sgxraiwskv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#sgxraiwskv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgxraiwskv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#sgxraiwskv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#sgxraiwskv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgxraiwskv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#sgxraiwskv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgxraiwskv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#sgxraiwskv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-left: 4px;\n  padding-right: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgxraiwskv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#sgxraiwskv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#sgxraiwskv .gt_left {\n  text-align: left;\n}\n\n#sgxraiwskv .gt_center {\n  text-align: center;\n}\n\n#sgxraiwskv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#sgxraiwskv .gt_font_normal {\n  font-weight: normal;\n}\n\n#sgxraiwskv .gt_font_bold {\n  font-weight: bold;\n}\n\n#sgxraiwskv .gt_font_italic {\n  font-style: italic;\n}\n\n#sgxraiwskv .gt_super {\n  font-size: 65%;\n}\n\n#sgxraiwskv .gt_footnote_marks {\n  font-style: italic;\n  font-weight: normal;\n  font-size: 75%;\n  vertical-align: 0.4em;\n}\n\n#sgxraiwskv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#sgxraiwskv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#sgxraiwskv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#sgxraiwskv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#sgxraiwskv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#sgxraiwskv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\">\n  \n  <thead class=\"gt_col_headings\">\n    <tr>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">inst</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">time</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">status</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">age</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">sex</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">ph.ecog</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">ph.karno</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">pat.karno</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">meal.cal</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\">wt.loss</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">306</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">74</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">100</td>\n<td class=\"gt_row gt_right\">1175</td>\n<td class=\"gt_row gt_right\">NA</td></tr>\n    <tr><td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">455</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">68</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">1225</td>\n<td class=\"gt_row gt_right\">15</td></tr>\n    <tr><td class=\"gt_row gt_right\">3</td>\n<td class=\"gt_row gt_right\">1010</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">56</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">15</td></tr>\n    <tr><td class=\"gt_row gt_right\">5</td>\n<td class=\"gt_row gt_right\">210</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">57</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">60</td>\n<td class=\"gt_row gt_right\">1150</td>\n<td class=\"gt_row gt_right\">11</td></tr>\n    <tr><td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">883</td>\n<td class=\"gt_row gt_right\">2</td>\n<td class=\"gt_row gt_right\">60</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">0</td>\n<td class=\"gt_row gt_right\">100</td>\n<td class=\"gt_row gt_right\">90</td>\n<td class=\"gt_row gt_right\">NA</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n    <tr><td class=\"gt_row gt_right\">12</td>\n<td class=\"gt_row gt_right\">1022</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">74</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">1</td>\n<td class=\"gt_row gt_right\">50</td>\n<td class=\"gt_row gt_right\">80</td>\n<td class=\"gt_row gt_right\">513</td>\n<td class=\"gt_row gt_right\">0</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n## Modelo de Cox\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste1 <- coxph(Surv(time,status==2) ~ age + sex + ph.ecog + ph.karno +\n                   pat.karno + meal.cal + wt.loss, data=dados)\ncoef(ajuste1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          age           sex       ph.ecog      ph.karno     pat.karno \n 1.064919e-02 -5.508521e-01  7.341767e-01  2.245506e-02 -1.241655e-02 \n     meal.cal       wt.loss \n 3.329025e-05 -1.433061e-02 \n```\n:::\n\n```{.r .cell-code}\nlogLik(ajuste1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'log Lik.' -498.7519 (df=7)\n```\n:::\n:::\n\n\nAs funções coef e loglik nos dão detalhes do modelo ajustado.\n\n## Resultados do ajuste\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ajuste1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, status == 2) ~ age + sex + ph.ecog + \n    ph.karno + pat.karno + meal.cal + wt.loss, data = dados)\n\n  n= 168, number of events= 121 \n   (60 observations deleted due to missingness)\n\n                coef  exp(coef)   se(coef)      z Pr(>|z|)   \nage        1.065e-02  1.011e+00  1.161e-02  0.917  0.35906   \nsex       -5.509e-01  5.765e-01  2.008e-01 -2.743  0.00609 **\nph.ecog    7.342e-01  2.084e+00  2.233e-01  3.288  0.00101 **\nph.karno   2.246e-02  1.023e+00  1.124e-02  1.998  0.04574 * \npat.karno -1.242e-02  9.877e-01  8.054e-03 -1.542  0.12316   \nmeal.cal   3.329e-05  1.000e+00  2.595e-04  0.128  0.89791   \nwt.loss   -1.433e-02  9.858e-01  7.771e-03 -1.844  0.06518 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n          exp(coef) exp(-coef) lower .95 upper .95\nage          1.0107     0.9894    0.9880    1.0340\nsex          0.5765     1.7347    0.3889    0.8545\nph.ecog      2.0838     0.4799    1.3452    3.2277\nph.karno     1.0227     0.9778    1.0004    1.0455\npat.karno    0.9877     1.0125    0.9722    1.0034\nmeal.cal     1.0000     1.0000    0.9995    1.0005\nwt.loss      0.9858     1.0144    0.9709    1.0009\n\nConcordance= 0.651  (se = 0.029 )\nLikelihood ratio test= 28.33  on 7 df,   p=2e-04\nWald test            = 27.58  on 7 df,   p=3e-04\nScore (logrank) test = 28.41  on 7 df,   p=2e-04\n```\n:::\n:::\n\n\nO ajuste com todas as variáveis mostrou que 60 observações foram eliminadas devido a dados ausentes. \n\n## Reavaliando o modelo de Cox\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste2 <- coxph(Surv(time,status==2) ~ age + sex + ph.ecog + ph.karno +\n                   pat.karno + wt.loss, data=dados)\ncoef(ajuste2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        age         sex     ph.ecog    ph.karno   pat.karno     wt.loss \n 0.01305840 -0.62516673  0.67522724  0.02011588 -0.01474279 -0.01324331 \n```\n:::\n\n```{.r .cell-code}\nlogLik(ajuste2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'log Lik.' -640.4764 (df=6)\n```\n:::\n:::\n\n\nNeste modelo eliminamos a variável meat.cal, pois seu p-valor indicou que ela não era estatisticamente significativa.\n\n## Resultados do modelo reavaliado\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ajuste2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, status == 2) ~ age + sex + ph.ecog + \n    ph.karno + pat.karno + wt.loss, data = dados)\n\n  n= 210, number of events= 148 \n   (18 observations deleted due to missingness)\n\n               coef exp(coef)  se(coef)      z Pr(>|z|)    \nage        0.013058  1.013144  0.009866  1.324 0.185639    \nsex       -0.625167  0.535172  0.178703 -3.498 0.000468 ***\nph.ecog    0.675227  1.964479  0.198735  3.398 0.000680 ***\nph.karno   0.020116  1.020320  0.010178  1.976 0.048111 *  \npat.karno -0.014743  0.985365  0.007300 -2.019 0.043440 *  \nwt.loss   -0.013243  0.986844  0.007009 -1.889 0.058836 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n          exp(coef) exp(-coef) lower .95 upper .95\nage          1.0131     0.9870    0.9937    1.0329\nsex          0.5352     1.8686    0.3770    0.7596\nph.ecog      1.9645     0.5090    1.3307    2.9001\nph.karno     1.0203     0.9801    1.0002    1.0409\npat.karno    0.9854     1.0149    0.9714    0.9996\nwt.loss      0.9868     1.0133    0.9734    1.0005\n\nConcordance= 0.656  (se = 0.025 )\nLikelihood ratio test= 37.2  on 6 df,   p=2e-06\nWald test            = 36.49  on 6 df,   p=2e-06\nScore (logrank) test = 37.59  on 6 df,   p=1e-06\n```\n:::\n:::\n\n\nVeja que ao eliminar meat.cal passamos a ter somente 18 observações eliminadas devido a dados ausentes.\n\n\n## Eliminando dados faltantes\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndados1 <- na.omit(dados)\najuste3 <- coxph(Surv(time,status==2) ~ age + sex + ph.ecog + ph.karno +\n                   pat.karno + meal.cal + wt.loss, data=dados1)\nlogLik(ajuste3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'log Lik.' -494.0344 (df=7)\n```\n:::\n:::\n\n\nObserve que modelos com números diferentes de observações não podem ser comparados, desta forma, inicialmente vamos eliminar os dados ausentes.\nPosteriormente devemos rever este ponto, pois ao eliminar observações podemos estar afetando a signicância de algumas variáveis explicativas.\n\n## Resultados do ajuste\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ajuste3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, status == 2) ~ age + sex + ph.ecog + \n    ph.karno + pat.karno + meal.cal + wt.loss, data = dados1)\n\n  n= 167, number of events= 120 \n\n                coef  exp(coef)   se(coef)      z Pr(>|z|)   \nage        1.080e-02  1.011e+00  1.160e-02  0.931  0.35168   \nsex       -5.536e-01  5.749e-01  2.016e-01 -2.746  0.00603 **\nph.ecog    7.395e-01  2.095e+00  2.250e-01  3.287  0.00101 **\nph.karno   2.244e-02  1.023e+00  1.123e-02  1.998  0.04575 * \npat.karno -1.207e-02  9.880e-01  8.116e-03 -1.488  0.13685   \nmeal.cal   2.835e-05  1.000e+00  2.594e-04  0.109  0.91298   \nwt.loss   -1.420e-02  9.859e-01  7.766e-03 -1.828  0.06748 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n          exp(coef) exp(-coef) lower .95 upper .95\nage          1.0109     0.9893    0.9881    1.0341\nsex          0.5749     1.7395    0.3872    0.8534\nph.ecog      2.0950     0.4773    1.3479    3.2560\nph.karno     1.0227     0.9778    1.0004    1.0455\npat.karno    0.9880     1.0121    0.9724    1.0038\nmeal.cal     1.0000     1.0000    0.9995    1.0005\nwt.loss      0.9859     1.0143    0.9710    1.0010\n\nConcordance= 0.653  (se = 0.029 )\nLikelihood ratio test= 28.16  on 7 df,   p=2e-04\nWald test            = 27.5  on 7 df,   p=3e-04\nScore (logrank) test = 28.31  on 7 df,   p=2e-04\n```\n:::\n:::\n\n\nA variável meat.cal continua sem significância estatística. \n\n## Modelo sem meat.cal\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste4 <- coxph(Surv(time,status==2) ~ age + sex + ph.ecog + ph.karno +\n                   pat.karno + wt.loss, data=dados1)\nlogLik(ajuste4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'log Lik.' -494.0404 (df=6)\n```\n:::\n:::\n\n\nMeat.cal foi retirada do ajuste\n\n## Resultados do ajuste\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary(ajuste4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, status == 2) ~ age + sex + ph.ecog + \n    ph.karno + pat.karno + wt.loss, data = dados1)\n\n  n= 167, number of events= 120 \n\n               coef exp(coef)  se(coef)      z Pr(>|z|)   \nage        0.010589  1.010645  0.011429  0.926  0.35419   \nsex       -0.556616  0.573145  0.199666 -2.788  0.00531 **\nph.ecog    0.738572  2.092944  0.224746  3.286  0.00102 **\nph.karno   0.022394  1.022647  0.011218  1.996  0.04590 * \npat.karno -0.011912  0.988159  0.007974 -1.494  0.13522   \nwt.loss   -0.014200  0.985901  0.007783 -1.824  0.06808 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n          exp(coef) exp(-coef) lower .95 upper .95\nage          1.0106     0.9895    0.9883    1.0335\nsex          0.5731     1.7448    0.3875    0.8477\nph.ecog      2.0929     0.4778    1.3473    3.2513\nph.karno     1.0226     0.9779    1.0004    1.0454\npat.karno    0.9882     1.0120    0.9728    1.0037\nwt.loss      0.9859     1.0143    0.9710    1.0011\n\nConcordance= 0.653  (se = 0.029 )\nLikelihood ratio test= 28.15  on 6 df,   p=9e-05\nWald test            = 27.51  on 6 df,   p=1e-04\nScore (logrank) test = 28.31  on 6 df,   p=8e-05\n```\n:::\n:::\n\n\nAdotando o nível de significância de 0,10, veja que agora pat.karno não é estatisticamente significativa!\nNa amostra original ela era estatisticamente significativa.\n\n## Teste da Razão de verossimilhança\n\nQuando os modelos são encaixados e estamos com amostras iguais, podemos usar o teste da razão de verossimilhança\n\n\n::: {.cell}\n\n```{.r .cell-code}\nTRV <- 2*(logLik(ajuste3) - logLik(ajuste4))\n1 - pchisq(TRV[1],1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9131696\n```\n:::\n\n```{.r .cell-code}\n# Posso obter o mesmo resultado com a Anova\nanova(ajuste3,ajuste4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(time, status == 2)\n Model 1: ~ age + sex + ph.ecog + ph.karno + pat.karno + meal.cal + wt.loss\n Model 2: ~ age + sex + ph.ecog + ph.karno + pat.karno + wt.loss\n   loglik  Chisq Df Pr(>|Chi|)\n1 -494.03                     \n2 -494.04 0.0119  1     0.9132\n```\n:::\n:::\n\n\n## Modelos não encaixados\n\n\n::: {.cell}\n\n```{.r .cell-code}\najuste5 <- coxph(Surv(time,status==2) ~ age + ph.karno + wt.loss,\n                 data=dados1)\ncoef(ajuste5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         age     ph.karno      wt.loss \n 0.014614112 -0.008985812 -0.001936254 \n```\n:::\n\n```{.r .cell-code}\najuste6 <- coxph(Surv(time,status==2) ~ sex + ph.ecog + pat.karno, data=dados1)\ncoef(ajuste6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         sex      ph.ecog    pat.karno \n-0.494861735  0.389220202 -0.007463256 \n```\n:::\n:::\n\n\n## Comparando modelo com o AIC e BIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nAIC(ajuste5,ajuste6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        df      AIC\najuste5  3 1017.267\najuste6  3 1001.862\n```\n:::\n\n```{.r .cell-code}\nBIC(ajuste5,ajuste6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        df      BIC\najuste5  3 1025.629\najuste6  3 1010.225\n```\n:::\n:::\n\n\nA comparação de modelos não encaixados pode ser feita através do AIC ou do BIC. Observe que os modelo devem ter o mesmo tamanho de amostra.\n\n## Utilizando o stepAIC\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(MASS)\nnovoajuste <- stepAIC(ajuste4, direction = \"backward\", trace=FALSE)\nsummary(novoajuste)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, status == 2) ~ sex + ph.ecog + ph.karno + \n    pat.karno + wt.loss, data = dados1)\n\n  n= 167, number of events= 120 \n\n               coef exp(coef)  se(coef)      z Pr(>|z|)   \nsex       -0.558190  0.572244  0.199202 -2.802  0.00508 **\nph.ecog    0.742983  2.102197  0.227604  3.264  0.00110 **\nph.karno   0.020366  1.020575  0.011080  1.838  0.06604 . \npat.karno -0.012401  0.987675  0.007978 -1.554  0.12008   \nwt.loss   -0.014494  0.985611  0.007693 -1.884  0.05957 . \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n          exp(coef) exp(-coef) lower .95 upper .95\nsex          0.5722     1.7475    0.3873    0.8456\nph.ecog      2.1022     0.4757    1.3457    3.2841\nph.karno     1.0206     0.9798    0.9987    1.0430\npat.karno    0.9877     1.0125    0.9724    1.0032\nwt.loss      0.9856     1.0146    0.9709    1.0006\n\nConcordance= 0.658  (se = 0.029 )\nLikelihood ratio test= 27.28  on 5 df,   p=5e-05\nWald test            = 26.89  on 5 df,   p=6e-05\nScore (logrank) test = 27.64  on 5 df,   p=4e-05\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {
      "include-after-body": [
        "\r\n<script>\r\n  // htmlwidgets need to know to resize themselves when slides are shown/hidden.\r\n  // Fire the \"slideenter\" event (handled by htmlwidgets.js) when the current\r\n  // slide changes (different for each slide format).\r\n  (function () {\r\n    // dispatch for htmlwidgets\r\n    function fireSlideEnter() {\r\n      const event = window.document.createEvent(\"Event\");\r\n      event.initEvent(\"slideenter\", true, true);\r\n      window.document.dispatchEvent(event);\r\n    }\r\n\r\n    function fireSlideChanged(previousSlide, currentSlide) {\r\n      fireSlideEnter();\r\n\r\n      // dispatch for shiny\r\n      if (window.jQuery) {\r\n        if (previousSlide) {\r\n          window.jQuery(previousSlide).trigger(\"hidden\");\r\n        }\r\n        if (currentSlide) {\r\n          window.jQuery(currentSlide).trigger(\"shown\");\r\n        }\r\n      }\r\n    }\r\n\r\n    // hookup for slidy\r\n    if (window.w3c_slidy) {\r\n      window.w3c_slidy.add_observer(function (slide_num) {\r\n        // slide_num starts at position 1\r\n        fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);\r\n      });\r\n    }\r\n\r\n  })();\r\n</script>\r\n\r\n"
      ]
    },
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}